panel/api/urls.py
from django.urls import path, include
from rest_framework import routers

from panel.api import views

router = routers.DefaultRouter()
router.register('measurements', views.MeasurementViewSet, basename='Measurement')
router.register('profile', views.ProfileViewSet, basename='Profile')
router.register('signature', views.SignatureViewSet, basename='Signature'),

urlpatterns = [
    path('', include(router.urls)),
]

panel/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import TemplateView

from panel import views
from .decorators import whether_profile_set

urlpatterns = [
    path('', login_required(whether_profile_set(views.DashboardView.as_view())), name='dashboard'),
    path('measurements/new', login_required(whether_profile_set(views.NewMeasurementView.as_view())), name='new'),
    path('measurements/<slug:pk>/delete', login_required(whether_profile_set(views.DeleteMeasurementView.as_view())),
         name='delete'),
    path('settings', login_required(views.SettingsView.as_view()), name='settings'),
    path('charts', login_required(whether_profile_set(views.ChartsView.as_view())), name='charts'),
    path('measurements/<slug:pk>/', login_required(whether_profile_set(views.DetailMeasurementView.as_view())),
         name='detail'),
    path('instruction/',
         login_required(whether_profile_set(TemplateView.as_view(template_name="panel/instruction.html"))),
         name='instruction'),
    path('ajax-generating-done/', views.get_if_generated, name="ajax-charts"),
]

slimmerme/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('dashboard/', include('panel.urls')),
                  path('accounts/', include('account.urls')),
                  path('', TemplateView.as_view(template_name='index.html'),
                       name="home"),
                  path('api/', include('panel.api.urls'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

panel/models.py
from datetime import date

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    height = models.IntegerField(blank=True, default=0, verbose_name="Wzrost")
    date_of_birth = models.DateField(blank=True, verbose_name="Data urodzenia")
    sex = models.CharField(null=True, blank=False, max_length=1, choices=(('M', 'mężczyzna'), ('F', 'kobieta')),
                           verbose_name="płeć")
    chart_js_code = models.TextField(null=True)
    goal_weight = models.FloatField(blank=True, null=True, validators=[MinValueValidator(0)], verbose_name="")

    @property
    def age(self):
        today = date.today()
        return today.year - self.date_of_birth.year - (
                (today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))

    @property
    def goal(self):
        if self.goal_weight:
            return self.goal_weight
        return self.ideal_weight

    @property
    def ideal_weight(self):
        # Lorentz's algorithm
        if self.sex == 'kobieta':
            return self.height - 100 - ((self.height - 150) / 2)
        return self.height - 100 - ((self.height - 150) / 4)

    def __str__(self):
        return 'Profil użytkownika {}'.format(self.user.username)


class Measurement(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='measurements')
    weight = models.FloatField(blank=True, null=True, validators=[MinValueValidator(0)], verbose_name="Masa ciała")
    bf_percent = models.FloatField(blank=True, null=True, validators=[MinValueValidator(0), MaxValueValidator(100)],
                                   verbose_name="Procent tkanki tłuszczowej")
    created_at = models.DateTimeField(auto_now=True)

    @property
    def bmi(self):
        try:
            return round(self.weight / ((self.profile.height / 100) ** 2), 2)
        except (ZeroDivisionError, TypeError):
            return "---"

    def __str__(self):
        return "Pomiar z {}".format(timezone.localtime(self.created_at).strftime('%H:%M %d.%m.%y'))


class Signature(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    signature = models.IntegerField(default=0)

panel/forms.py
from datetime import date
from math import sqrt

from bootstrap_datepicker_plus import DatePickerInput
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator

from .models import Profile, Measurement


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('height', 'sex', 'date_of_birth', 'goal_weight')
        widgets = {
            'date_of_birth': DatePickerInput(format='%Y-%m-%d'),
        }

    def clean_date_of_birth(self):
        value = self.cleaned_data.get("date_of_birth")
        today = date.today()
        age = today.year - value.year - (
                (today.month, today.day) < (value.month, value.day))
        if age < 18:
            raise ValidationError("Musisz mieć co najmniej 18 lat.")
        elif age > 200:
            raise ValidationError("I tak ci nie uwierzymy, że masz tyle lat :)")

        return value


class ChartsForm(forms.Form):
    chart_type = forms.ChoiceField(choices=(
        (7, "tydzień"), (14, "dwa tygodnie"), (31, "miesiąc"), (62, "dwa miesiące"),
        (183, "sześć miesięcy"), (365, "rok"), ("inny", "inny okres czasu")), label="", initial=14, )
    different = forms.IntegerField(label="", widget=forms.NumberInput(
        attrs={"placeholder": "Podaj dokładną liczbę dni do generacji", "style": "display:none;"}),
                                   required=False, validators=[MinValueValidator(1)])


class MenMeasurementForm(forms.ModelForm):
    thigh = forms.FloatField(validators=[MinValueValidator(0)], required=False, label="Udo")
    pectoral = forms.FloatField(validators=[MinValueValidator(0)], required=False, label="Klatka piersiowa")
    abdominal = forms.FloatField(validators=[MinValueValidator(0)], required=False, label="Brzuch")

    class Meta:
        model = Measurement
        fields = ("weight", "bf_percent")

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.profile = self.request.user.profile
        instance = self.jackson_pallock(instance)
        if commit:
            instance.save()
        return instance

    def jackson_pallock(self, instance):
        if self.cleaned_data.get("weight", False) and self.cleaned_data.get("thigh", False) and self.cleaned_data.get(
                "pectoral", False) and self.cleaned_data.get("abdominal", False):
            summ = self.cleaned_data.get("thigh", 0) + self.cleaned_data.get("pectoral", 0) + self.cleaned_data.get(
                "abdominal", 0)
            age = self.request.user.profile.age
            body_density = 1.10938 - (0.0008267 * summ) + (0.0000016 * sqrt(summ)) - (0.0002574 * age)
            fat = (495 / body_density) - 450
            instance.bf_percent = round(fat, 2)

        return instance


class FemaleMeasurementForm(MenMeasurementForm):
    tricep = forms.FloatField(validators=[MinValueValidator(0)], required=False, label="Triceps")
    suprailiac = forms.FloatField(validators=[MinValueValidator(0)], required=False, label="Skos brzucha")
    pectoral = None
    abdominal = None

    def jackson_pallock(self, instance):
        if self.cleaned_data.get("weight", False) and self.cleaned_data.get("thigh", False) and self.cleaned_data.get(
                "tricep", False) and self.cleaned_data.get("suprailiac", False):
            summ = self.cleaned_data.get("thigh", 0) + self.cleaned_data.get("tricep", 0) + self.cleaned_data.get(
                "suprailiac", 0)
            age = self.request.user.profile.age
            body_density = 1.0994921 - (0.0009929 * summ) + (0.0000023 * sqrt(summ)) - (0.0001392 * age)
            fat = (495 / body_density) - 450
            instance.bf_percent = round(fat, 2)

        return instance

panel/api/views.py
from rest_framework import viewsets
from rest_framework.authentication import BasicAuthentication
from rest_framework.permissions import IsAuthenticated

from panel.api.serializers import MeasurementSerializer, ProfileSerializer, SignatureSerializer
from panel.models import Measurement, Profile, Signature


class MeasurementViewSet(viewsets.ModelViewSet):
    authentication_classes = (BasicAuthentication,)
    permission_classes = (IsAuthenticated,)
    serializer_class = MeasurementSerializer

    def get_queryset(self):
        return Measurement.objects.filter(profile__user=self.request.user)

    def perform_create(self, serializer):
        serializer.save(profile=self.request.user.profile)


class ProfileViewSet(viewsets.ReadOnlyModelViewSet):
    authentication_classes = (BasicAuthentication,)
    permission_classes = (IsAuthenticated,)
    serializer_class = ProfileSerializer

    def get_queryset(self):
        return Profile.objects.filter(user=self.request.user)


class SignatureViewSet(viewsets.ReadOnlyModelViewSet):
    authentication_classes = (BasicAuthentication,)
    permission_classes = (IsAuthenticated,)
    serializer_class = SignatureSerializer

    def get_queryset(self):
        return Signature.objects.filter(user=self.request.user)

panel/views.py
from django.core.exceptions import PermissionDenied
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView, FormView

from .charts import generate_chart
from .forms import ProfileForm, ChartsForm, MenMeasurementForm, FemaleMeasurementForm
from .models import Measurement, Profile


class DashboardView(ListView):
    model = Measurement
    template_name = "panel/dashboard_view.html"

    def get_queryset(self):
        profile = self.request.user.profile
        return self.model.objects.filter(profile=profile).order_by("-created_at")


class NewMeasurementView(CreateView):
    template_name = "panel/new_measurement.html"
    success_url = reverse_lazy("dashboard")

    def get_form_class(self, form_class=None):
        if self.request.user.profile.sex == "M":
            return MenMeasurementForm
        else:
            return FemaleMeasurementForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class DeleteMeasurementView(DeleteView):
    model = Measurement
    success_url = reverse_lazy("dashboard")
    template_name = "panel/delete_measurement.html"


class SettingsView(UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = "panel/settings.html"
    success_url = reverse_lazy("dashboard")

    def get_object(self, queryset=None):
        return self.request.user.profile


class DetailMeasurementView(DetailView):
    model = Measurement
    template_name = "panel/detail.html"

    def get(self, *args, **kwargs):
        if not self.get_object().profile.user.id == self.request.user.id:
            raise PermissionDenied
        return super().get(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = Measurement.objects.filter(profile__user=self.request.user).order_by("-created_at")
        return context


class ChartsView(FormView):
    form_class = ChartsForm
    template_name = "panel/charts_view.html"
    chart_type = 14

    def get_context_data(self, **kwargs):
        contex = super().get_context_data()

        if self.chart_type == 14:
            contex["chart_js_code"] = self.profile.chart_js_code
        else:
            contex["chart_js_code"] = generate_chart(self.profile, self.chart_type)

        return contex

    def get(self, request, *args, **kwargs):
        self.profile = self.request.user.profile
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            try:
                self.chart_type = int(form.cleaned_data["chart_type"])
            except ValueError:
                self.chart_type = int(form.cleaned_data["different"])

        return self.get(request, *args, **kwargs)


def get_if_generated(request):
    profile = request.user.profile
    if profile.chart_js_code == 'spinner':
        done = False
    else:
        done = True

    return JsonResponse({'done': done, })

panel/templates/panel/bmi_modal.html
<div class="modal fade" id="bmiModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">BMI</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                BMI jest bardzo prosty w użyciu, jednak nie uwzględnia on indywidualnej budowy ciała. Jest dosyć
                niedokładnym wskaźnikiem niedowagi i nadwagi oraz ryzyk chorób z nimi związanych. Kulturyści mogą mieć
                BMI wskazujące na skrajną otyłość, posiadając jednocześnie bardzo mało tkanki tłuszczowej. Z drugiej
                strony, BMI zupełnie zdrowych, szczupłych i wysokich lekkoatletów może wskazywać na skrajną niedowagę
                (np. BMI Yohanna Diniza przy wzroście 185 cm i wadze 59 kg wyniesie 17,24).
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Rozumiem</button>
            </div>
        </div>
    </div>
</div>

panel/templates/panel/charts_view.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block extra_style %}
    <link rel="stylesheet" href="{% static 'panel/css/view_with_charts.min.css' %}">
{% endblock %}
{% block content %}
    <main role="main" class="container jumbotron" style="margin-bottom: -20px;padding-left:2rem;padding-right: 2rem;">
        <form method="post">{% csrf_token %}
            <h3><b>Wybierz okres czasu, z którego chcesz wygenerować wykres</b></h3>
            {% bootstrap_form form %}
            <input class="btn btn-primary" type="submit" value="Generuj">
        </form>
        <hr/>
    </main>
    <main role="main" class="jumbotron-not-on-mobile container" style="background-color: #e9ecef; margin-top: -10px;">
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        {% autoescape off %}
            {{ chart_js_code }}
        {% endautoescape %}
    </main>

{% endblock %}
{% block js %}
    <script src="{% static 'panel/js/charts_view.min.js' %}"></script>
    <script src="{% static 'panel/js/view_with_chart.min.js' %}"></script>
{% endblock %}

panel/templates/panel/dashboard_view.html
{% extends "base.html" %}
{% load static %}
{% load design_filters %}
{% block extra_head %}
    <link rel="stylesheet" href="{% static 'panel/css/view_with_charts.min.css' %}">
{% endblock %}
{% block content %}
    <main role="main" class="container">
        <div class="jumbotron" style="margin-bottom: -30px;">
            <a class="btn btn-success btn-block" href="{% url 'new' %}">Dodaj nowy pomiar ręcznie </a>
            {% if  request.user.profile.chart_js_code %}
                </div> </main>
                <div class="jumbotron-not-on-mobile container" align="center">
                    {% if request.user.profile.chart_js_code|first != 'x' %}
                        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
                        {% autoescape off %}
                            {{ request.user.profile.chart_js_code }}
                        {% endautoescape %}
                    {% else %}
                        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                            <span class="sr-only">Loading...</span></div>
                        generowanie wykresu...
                    {% endif %}
                </div>
                <main role="main" class="container">
                <div class="jumbotron" style="margin-top: -20px;">
                <a href="{% url 'charts' %}" class='btn btn-outline-primary' style='margin-bottom: 25px;'>Wygeneruj
                    więcej wykresów &#10148;
                </a>
            {% else %}
                Dodaj swój pierwszy pomiar aby wygenerować wykres.
            {% endif %}
            <h1>Ostatnie pomiary</h1>
            <div class=" container">
                <ul class="list-group" style="overflow: auto; max-height:200px">
                    {% for measurement in object_list %}
                        <a href="{% url 'detail' measurement.id %}"
                           class="list-group-item list-group-item-action">{{ measurement.created_at }} {{ measurement.weight|none_to_dash }}kg {{ measurement.bf_percent|none_to_dash }}%</a>
                    {% empty %}
                        Brak pomiarów. Dodaj pomiar!
                    {% endfor %}
                </ul>
            </div>
            </div>
            </main>
{% endblock %}
{% block js %}
    <script>
        {% if request.user.profile.chart_js_code|first == 'x' %}
            window.setInterval(function () {
                $.ajax({
                    url: "{% url 'ajax-charts' %}",
                    data: {
                        '': ''
                    },

                    dataType: 'json',
                    success: function (data) {
                        if (data.done) {
                            console.log(data);
                            location.reload()
                        }
                    }
                })
            }, 100);
        {% endif %}
    </script>
    <script src="{% static 'panel/js/view_with_chart.min.js' %}"></script>
{% endblock %}

panel/templates/panel/delete_measurement.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <main role="main" class="container jumbotron">
        <form method="post">{% csrf_token %}
            <h1 class="display-4">Czy jesteś pewien że chcesz usunąć pomiar z <br/>{{ object.created_at }}?</h1>
            <input class="btn btn-danger btn-lg btn-block" type="submit" value="Usuń">
        </form>
    </main>

{% endblock %}

panel/templates/panel/detail.html
{% extends "base.html" %}
{% load design_filters %}
{% load static %}
{% block content %}
    {% include 'panel/bmi_modal.html' %}
    <main role="main" class="container">
        <div class="jumbotron">
            <div class="row">
                <div class="btn btn-primary disabled btn-block">
                    {{ object }}
                </div>
            </div>
            <div class="row group">
                <div class="col">
                    <div class="card border-primary mb-3" style="max-width: 18rem;">
                        <div class="card-header text-primary">Masa ciała</div>
                        <div class="card-body text-primary">
                            <h5 class="card-title">{{ object.weight|none_to_dash }} kg</h5>
                            {#                            <p class="card-text">Ważyłeś {{ object.weight }} kilogramów</p>#}
                        </div>
                    </div>
                </div>
                <div class="col">

                    <div class="card border-primary mb-3" style="max-width: 18rem;">
                        <div class="card-header text-primary">Tkanka tłuszczowa</div>
                        <div class="card-body">
                            <h5 class="card-title text-primary">{{ object.bf_percent|none_to_dash }}%</h5>
                            {#                            <p class="card-text">Twoje ciało składało się w {{ object.bf_percent }}% z tłuszczu.</p>#}
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card text-light {{ object.bmi|bmi_class }} mb-3" data-toggle="modal"
                         data-target="#bmiModal"
                         title="Kliknij aby przeczytać więcej"
                         style="max-width: 18rem;">
                        <div class="card-header"><abbr title="Kliknij aby przeczytać więcej">BMI</abbr></div>
                        <div class="card-body">
                            <h5 class="card-title">{{ object.bmi }}</h5>
                            <p class="card-text">Twój wskaźnik masy ciała wskazuje {{ object.bmi|bmi_description }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row group">
                <div class="col ">
                    <a class="btn btn-success btn-block" href="{% url 'new' %}">Dodaj nowy pomiar ręcznie</a>
                    <a href="{% url 'delete' object.id %}" class="btn btn-danger btn-block text-light">Usuń ten pomiar
                        &#10008;</a>
                </div>
            </div>
            <h2 class="display-5" style="margin-top: 25px;">Ostatnie pomiary</h2>
            <div class="container">
                <ul class="list-group" style="overflow: auto; max-height:200px">
                    {% for measurement in object_list %}
                        {% if measurement == object %}
                            <a href="{% url 'detail' measurement.id %}"
                               class="list-group-item list-group-item-action active">{{ measurement.created_at }} {{ measurement.weight|none_to_dash }}kg {{ measurement.bf_percent|none_to_dash }}%</a>
                        {% else %}
                            <a href="{% url 'detail' measurement.id %}"
                               class="list-group-item list-group-item-action">{{ measurement.created_at }} {{ measurement.weight|none_to_dash }}kg {{ measurement.bf_percent|none_to_dash }}%</a>
                        {% endif %}
                    {% empty %}
                        Brak pomiarów. Dodaj pomiar!
                    {% endfor %}
                </ul>
            </div>
        </div>
    </main>
{% endblock %}

{% block js %}
    <script src="{% static 'panel/js/detail.min.js' %}"></script>
{% endblock %}

panel/templates/panel/goal_modal.html
<div class="modal fade" id="goalModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Cel</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Wybierz docelową masę, którą chcesz osiągnąć. Nie masz pomysłu? Jeśli pozostawisz to pole puste,
                zostanie wyliczona za pomocą algorytmu Lorenza.

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Okej</button>
            </div>
        </div>
    </div>
</div>

panel/templates/panel/instruction.html
{% extends 'base.html' %}
{% block content %}

    <div class="container jumbotron">
        {% if request.user.profile.sex == "M" %}
            <h1>Pomiary dla 3-punktowego testu tkanki tłuszczowej Jackson-Pollock. (Dla mężczyzn)</h1>
            <hr/>
            {% include "videos/men/tight.html" %}
            <hr/>
            {% include "videos/men/pectoral.html" %}
            <hr/>
            {% include "videos/men/abdominal.html" %}
        {% else %}
            <h1>Pomiary dla 3-punktowego testu tkanki tłuszczowej Jackson-Pollock. (Dla kobiet)</h1>
            <hr/>
            {% include "videos/women/tight.html" %}
            <hr/>
            {% include "videos/women/tricep.html" %}
            <hr/>
            {% include "videos/women/suprailiac.html" %}
        {% endif %}
        Powyższe filmy pochodzą ze strony <a href="https://www.conditiontime.pl">conditiontime.pl</a>
    </div>
{% endblock %}

panel/templates/panel/new_measurement.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load field_filters %}
{% load static %}
{% block content %}
    <main role="main" class="container jumbotron">
        {% include 'panel/pollock_modal.html' %}
        <form method="post">{% csrf_token %}
            {% bootstrap_field form.weight addon_after="<b>kg</b>" %}
            {% bootstrap_field form.bf_percent addon_after="<div class='input-group-text'><b>%</b></div><button aria-expanded='false' aria-controls='collapse' data-toggle='collapse' data-target='#collapse' class='btn btn-outline-secondary' type='button' id='append-btn'>Wylicz <i class='fas fa-calculator'></i></button>" %}
            <div id="collapse" class="collapse">
                <h3><abbr title="Klikniij, aby przeczytać więcej" data-toggle="modal"
                          data-target="#pollockModal">Jackson-Pollock m. 3-punktowa</abbr>:</h3>
                {% for field in form.visible_fields|exclude:'weight,bf_percent' %}
                    {% bootstrap_field field addon_after="<b>mm</b>" %}
                {% endfor %}
            </div>
            <input type="submit" class="btn btn-primary" value="Dodaj">
        </form>
    </main>
{% endblock %}
{% block js %}
    <script src="{% static 'panel/js/new_measurement.min.js' %}"></script>
{% endblock %}

panel/templates/panel/pollock_modal.html
<div class="modal fade" id="pollockModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Jackson-Pollock metoda 3-punktowa</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>3-punktowy test tkanki tłuszczowej Jackson-Pollock, opracowany przez dr Andrew Jacksona i M. L.
                    Pollocka, jest dość prostą metodą, którą można wykonać szybko i łatwo, bez specjalnego sprzętu i
                    szkolenia. Wszystko, czego potrzeba, to podstawowy zacisk fałdowy, waga łazienkowa i nasza strona.
                </p>
                <p>
                    Należy zauważyć, że test metodą Jackson-Pollock jest dość dokładny dla
                    większości ludzi. Jednakże ta metoda nie wylicza dobrze poziomu tkanki tłuszczowej u osób bardzo
                    szczupłych, w
                    tym kulturystów i sportowców wyczynowych. Więc jeśli masz przeciętną budowę, możesz rozważyć
                    wypróbowanie 3-punktowego testu tkanki tłuszczowej Jackson-Pollock.</p>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">OK</button>
                <a class="btn btn-primary" href="{% url 'instruction' %}">Instrukcja pomiarów</a>
            </div>
        </div>
    </div>
</div>

panel/templates/panel/settings.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    {{ form.media }}
    <main role="main" class="container jumbotron">
        {% include 'panel/goal_modal.html' %}
        <h1 class="display-5">Ustawienia profilu</h1>
        <form method="post">{% csrf_token %}
            {% bootstrap_form form exclude='goal_weight' %}
            <label for="id_goal_weight" data-toggle="modal"
                   data-target="#goalModal"><abbr title='Kliknij aby przeczytać'>Wymarzona masa (cel)</abbr></label>
            {% bootstrap_field form.goal_weight addon_after="<b>kg</b>" %}
            <input type="submit" class="btn btn-primary" value="Zmień">
        </form>
    </main>
{% endblock %}